name: Deploy FasAPI on Local PC

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Stop old stack
        run:
          if docker compose ps --services > /dev/null 2>&1; then
          echo "Stopping old running containers"
          docker compose down -v
          else
          echo "No containers running â€” skipping down"
          fi

      - name: Run tests
        run: docker compose run -rm fastapi pytest -xvs

      - name: Build and start new stack
        run: docker compose up --build - d

      - name: Health_check endpoint
        run:
          sleep 5
          curl - f http://localhost:8001/health_check