name: Deploy FasAPI on Local PC

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo SMTP_HOST=${{ secrets.SMTP_HOST }} > .env
          echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
          echo SMTP_USER=${{ secrets.SMTP_USER }} >> .env
          echo SMTP_PASS=${{ secrets.SMTP_PASS }} >> .env
          echo CACHE_HOST=${{ secrets.CACHE_HOST }} >> .env
          echo CACHE_PORT=${{ secrets.CACHE_PORT }} >> .env
          echo BROKER_URL=${{ secrets.BROKER_URL }} >> .env

      - name: Stop old stack
        run: |
          docker compose down -v 2>nul
          if %errorlevel% neq 0 echo "No containers to stop"
          exit /b 0

      - name: Run tests
        run: docker compose run --rm fastapi pytest -xvs

      - name: Build and start new stack
        run: docker compose up --build -d

      - name: Health_check endpoint
        run: |
          timeout /t 5 /nobreak >nul
          curl.exe -f http://localhost:8001/health_check