name: Deploy FasAPI on Local PC

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Stop old stack
        run: |
          if (docker compose ps --services 2>$null) {
            Write-Host "Stopping containers"
            docker compose down -v
          } else {
            Write-Host "No containers running"
          }

      - name: Run tests
        run: docker compose run --rm fastapi pytest -xvs

      - name: Build and start new stack
        run: docker compose up --build -d

      - name: Health_check endpoint
        run:
          sleep 5
          curl - f http://localhost:8001/health_check